# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh --host github.com
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: vim
gh_editor: vim
visual: vim
editor: vim
git_editor: vim
pager: "less"
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    il: issue list
    iv: issue view
    pv: pr view
    pl: pr list
    jonnieey: '!cp ~/.config/gh/hosts.yml.personal ~/.config/gh/hosts.yml && gh auth status'
    alx: '!cp ~/.config/gh/hosts.yml.alx ~/.config/gh/hosts.yml && gh auth status'
version: "1"
