#!/bin/sh
mydmenu() {
	rofi -dmenu -nb '#282c34' -nf '#abb2bf' -sb '#61afef' -sf '#282c34' -Y 350 -W 700 -X 300 -i -p "$1"
}
devices() {
	lsblk -a -o 'PATH,LABEL,FSAVAIL,SIZE,MOUNTPOINT'
}

no_of_devices() {
	devices | wc -l
}

device=$(devices | mydmenu | cut -d' ' -f1)

if [ -n "$device" ]; then
	if mount | grep -q "$device"; then
		msg=$(udisksctl unmount -b "$device")
		notify-send 'Unmount' "$msg"
	else
		msg=$(udisksctl mount -b "$device")
		notify-send 'Mount' "$msg"
	fi
fi
